DreamJob/Controllers/Favoris/FavorisController.cs
using DreamJob.Models;
using DreamJob.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DreamJob.Controllers.Favoris
{
    public class FavorisController : Controller
    {
        // GET: Account
        [Authorize]
        public ActionResult Index()
        {
            Dal dal = new Dal();
            FavorisViewModel vm = new FavorisViewModel
            {
                ListeDesFavoris = dal.ObtientUtilisateurFavoris(),
                ListeDesArticles = dal.ObtientTousLesArticles()
            };
            return View(vm);
        }

        public ActionResult AfficheFavoris()
        {
            Dal dal = new Dal();
            var favori = Request.QueryString["favori"];
            FavorisViewModel vm = new FavorisViewModel { };

            if (!String.IsNullOrEmpty(favori))
            {
                var result = dal.Favorise(Int32.Parse(favori));
                if (result == -1)
                    vm.InfoMessage = "L'offre a été retirée de vos favoris avec succès";
                else
                    vm.InfoMessage = "Une erreur s'est produite";
            }

            vm.ListeDesArticles = dal.ObtientTousLesArticles();
            vm.ListeDesFavoris = dal.ObtientUtilisateurFavoris();

            return PartialView(vm);
        }
    }
}

DreamJob/Controllers/Login/LoginController.cs
using DreamJob.Models;
using DreamJob.ViewModels;
using System.Web.Mvc;
using System.Web.Security;

namespace DreamJob.Controllers.Login
{

    public class LoginController : Controller
    {
        private Dal dal;

        // Constructeur externe
        public LoginController() : this(new Dal())
        {

        }

        // Constructeur interne
        private LoginController(Dal dalIoc)
        {
            dal = dalIoc;
        }

        // Route GET vers la vue partielle d'authentification
        public ActionResult Index()
        {
            HomeViewModel viewModel = new HomeViewModel { Authentifie = HttpContext.User.Identity.IsAuthenticated };
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                var name = HttpContext.User;
                viewModel.Utilisateur = dal.ObtenirUtilisateurParId(HttpContext.User.Identity.Name);
            }
            return View(viewModel);
        }

        // Route POST vers la vue partielle d'authentification (appelee lors d'une connexion)
        [HttpPost]
        public ActionResult Index(HomeViewModel viewModel)
        {
            // Si les donnees d'identification ont un format valide ...
            if (ModelState.IsValid)
            {
                Utilisateur utilisateur = dal.Authentifier(viewModel.Utilisateur.Prenom, viewModel.Utilisateur.MotDePasse);
                // et que l'utilisateur est dans la base de donnee
                if (utilisateur != null)
                {
                    // identifier l'utilisateur par un cookie
                    FormsAuthentication.SetAuthCookie(utilisateur.Id.ToString(), false);
                    viewModel.Authentifie = true;
                    // reactualiser la vue partielle d'indentification
                    return View(viewModel);
                }
                // Si l'utilisateur n'est pas dans la base de donnee ou que le mot de passe est incorrect, envoyer une erreur
                ModelState.AddModelError("Utilisateur.Prenom", "Prénom et/ou mot de passe incorrect(s)");
            }
            // Si le format n'est pas valide, renvoyer la ve partielle d'identification avec une erreur
            return View(viewModel);
        }

        // Route GET pour creer un compte (l'utilisateur a clique sur le lien pour creer un nouveau compte)
        public ActionResult CreerCompte()
        {
            return View();
        }

        // Route POST pour creer un compte (l'utilisateur envoie un nom et un mot de passe pour creer un compte)
        [HttpPost]
        public ActionResult CreerCompte(Utilisateur utilisateur)
        {
            // Si les donnees d'identification ont un format valide...
            if (ModelState.IsValid)
            {
                // ajouter l'utilisateur a la base de donnee
                int id = dal.AjouterUtilisateur(utilisateur.Prenom, utilisateur.MotDePasse);
                // identifier l'utilisateur par un cookie
                FormsAuthentication.SetAuthCookie(id.ToString(), false);
                // redirection vers la page d'origine
                return Redirect("/");
            }
            // sinon on reactualise la page de creation de compte
            return View(utilisateur);
        }

        // Route pour la deconnexion
        public ActionResult Deconnexion()
        {
            FormsAuthentication.SignOut();
            return Redirect("/");
        }

        // Methode permttant de determiner si le nom d'utilisateur existe deja
        [HttpPost]
        public JsonResult doesUserNameExist(Utilisateur Utilisateur)
        {
            var user = dal.ObtenirUtilisateur(Utilisateur.Prenom);
            return Json(user == null);
        }
    }
}

DreamJob/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container-fluid">
        <div class="row header">
            <ul class="nav nav-pills">
                <li>
                    @Html.ActionLink("Accueil", "Index", "Home", new object { }, new { @class = "" })
                </li>
                @if (@User.Identity.IsAuthenticated)
                {
                    <li>
                        @Html.ActionLink("Mon compte", "Index", "Account", new object { }, new { @class = "" })
                    </li>
                    <li>
                        @Html.ActionLink("Mes favoris", "Index", "Favoris", new object { }, new { @class = "" })
                    </li>
                    <li>
                        @Html.ActionLink("Se déconnecter", "Deconnexion", "Login", new object { }, new { @class = "" })
                    </li>
                }
                else
                {
                    <li>
                        @Html.ActionLink("Se connecter", "Index", "Login", new object { }, new { @class = "" })
                    </li>
                }
            </ul>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        
    </div>
    <footer>
        <p>LEBOUCHER Clément / LE BESCOND Baptiste</p>
    </footer>

    @*<script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>*@
    <script src="~/scripts/jquery-2.2.1.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
</body>
</html>